version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.21.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.8
  - dependency-name: next
    versions:
    - 10.0.7
  - dependency-name: polished
    versions:
    - 4.1.1
